repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  # Ruff version.
  rev: c60c980e561ed3e73101667fe8365c609d19a438 # v0.15.9
  hooks:
    - id: ruff-check
      args: [ --fix ]
    - id: ruff-format
